server:
  port: 8083
spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      username: user
      password: password
      database: profiles